# Github Recommended Settings
# markdown: kramdown
#
# # Blog Settings
lang: en
domain: chibby0ne.github.io
title: Antonio Gutierrez's Invetions
tagline: A mind needs books as a sword needs a whetstone, if it is to keep its edge
