# Github Recommended Settings
# markdown: kramdown
#
# # Blog Settings
lang: en
domain: chibby0ne.github.io
title: chibby0ne
tagline: He who controls the past controls the future. He who controls the present controls the past
