baseURL = "https://www.antoniojgutierrez.com/"
DefaultContentLanguage = "en" # Theme's display language, supports: en, fr, zh, zh-hant
languageCode = "en-us"
title = "Murmurations of Neurons"
copyright = "Antonio Gutierrez 2015-2021. CC-BY-NC 4.0"
theme = "diary"
googleAnalytics = "UA-55399960-1"

[markup]
  [markup.highlight]
    codeFences = true
    guessSyntax = false
    hl_Lines = ""
    lineNoStart = 1
    lineNos = false
    lineNumbersInTable = true
    noClasses = true
    style = "perldoc"
    tabWidth = 4

[params]
subtitle = "An exploration of ideas and thoughts on programming, computers, nature and life in general"
disqusShortname = "antoniojgutierrez"
github_username = "chibby0ne"
enableReadingTime = true
enableLaTeX = true
# Twitter Card and Open Graph settings
enableOpenGraph = true
enableTwitterCards = true
title = "Murmurations of Neurons" # will set 'og:site_name'
description = "An exploration of ideas and thoughts on programming, computers, nature and life in general"  # will set 'og:description'

[taxonomies]
   tag = "tags"
   category = "categories"

[[menu.main]]
name = "About me"
url = "/about"
weight = 1
[[menu.main]]
name = "Archive"
url = "/posts"
weight = 2
[[menu.main]]
name = "Categories"
url = "/categories"
weight = 3
[[menu.main]]
name = "Tags"
url = "/tags"
weight = 4
[[menu.main]]
name = "CV"
url = "/cv"
weight = 6
[[menu.main]]
name = "CTFs"
url = "https://github.com/chibby0ne/CTFs/blob/main/README.md"
weight = 7
[[menu.main]]
name = "RSS Feed"
url = "/index.xml"
weight = 100
